import type { AnalysisResult } from './types';

export const DEMO_RESULT: AnalysisResult = {
  id: 'demo-001',
  url: 'https://www.youtube.com/watch?v=demoVideoId',
  platform: 'youtube',
  analyzedAt: new Date().toISOString(),
  video: {
    id: 'demoVideoId',
    title: 'BREAKING: Major Policy Announcement Changes Everything',
    channelName: 'NewsNow24',
    viewCount: 847291,
    likeCount: 12400,
    commentCount: 3841,
    thumbnail: '',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    url: 'https://www.youtube.com/watch?v=demoVideoId',
  },
  comments: [
    { id: 'c1', author: 'PoliticsWatcher', text: 'This is exactly what I was talking about last week. The implications are massive.', likeCount: 234, publishedAt: new Date().toISOString(), isReply: false, botScore: 5, classification: 'human', signals: [] },
    { id: 'c2', author: 'user7823456', text: 'Great video! Check out my channel for more amazing content like this! https://bit.ly/xyz', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 89, classification: 'bot', signals: ['Promotional self-advertising language', 'Contains external URL', 'Auto-generated username pattern detected'] },
    { id: 'c3', author: 'user7823457', text: 'Great video! Check out my channel for more amazing content like this! https://bit.ly/xyz', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 94, classification: 'bot', signals: ['Exact duplicate of 8 other comments', 'Promotional self-advertising language', 'Contains external URL', 'Auto-generated username pattern detected'] },
    { id: 'c4', author: 'user7823458', text: 'Great video! Check out my channel for more amazing content like this! https://bit.ly/xyz', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 94, classification: 'bot', signals: ['Exact duplicate of 8 other comments', 'Promotional self-advertising language', 'Contains external URL', 'Auto-generated username pattern detected'] },
    { id: 'c5', author: 'Sarah Mitchell', text: 'I have been following this story for months. Finally some mainstream coverage.', likeCount: 89, publishedAt: new Date().toISOString(), isReply: false, botScore: 8, classification: 'human', signals: [] },
    { id: 'c6', author: 'TruthSeeker99', text: 'WAKE UP PEOPLE!!! THIS IS BIGGER THAN THEY ARE TELLING YOU!!!', likeCount: 12, publishedAt: new Date().toISOString(), isReply: false, botScore: 38, classification: 'suspicious', signals: ['Excessive capitalization', 'Repetitive punctuation pattern'] },
    { id: 'c7', author: 'acc283847291', text: 'This content is so informative. Share this everywhere so people know the truth!', likeCount: 1, publishedAt: new Date().toISOString(), isReply: false, botScore: 62, classification: 'bot', signals: ['Auto-generated username pattern detected', 'Near-identical to 5 other comments'] },
    { id: 'c8', author: 'acc283847292', text: 'This content is so informative. Share this everywhere so people know the truth!', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 75, classification: 'bot', signals: ['Exact duplicate of 4 other comments', 'Auto-generated username pattern detected'] },
    { id: 'c9', author: 'acc283847293', text: 'This content is very informative. Please share everywhere so people know the truth!', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 70, classification: 'bot', signals: ['Near-identical to 5 other comments', 'Auto-generated username pattern detected'] },
    { id: 'c10', author: 'JohnDavis_Real', text: 'Good analysis but you missed the point about the economic consequences.', likeCount: 45, publishedAt: new Date().toISOString(), isReply: false, botScore: 12, classification: 'human', signals: [] },
    { id: 'c11', author: 'MediaCritic42', text: 'Typical mainstream media spin. They never show the full picture.', likeCount: 67, publishedAt: new Date().toISOString(), isReply: false, botScore: 18, classification: 'human', signals: [] },
    { id: 'c12', author: 'newsbot4421', text: 'Subscribe for daily news updates! Click the link in bio!', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 91, classification: 'bot', signals: ['Promotional self-advertising language', 'Contains external URL', 'Auto-generated username pattern detected'] },
    { id: 'c13', author: 'ResearcherMike', text: 'The data they cited at 4:20 is from 2019. Needs context.', likeCount: 156, publishedAt: new Date().toISOString(), isReply: false, botScore: 4, classification: 'human', signals: [] },
    { id: 'c14', author: 'user9912345', text: '👍👍👍👍👍👍👍👍👍👍', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 55, classification: 'suspicious', signals: ['Generic low-effort comment', 'Unusually high emoji density'] },
    { id: 'c15', author: 'acc283847294', text: 'This content is very informative. Share this everywhere so people know the truth!', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 70, classification: 'bot', signals: ['Near-identical to 5 other comments', 'Auto-generated username pattern detected'] },
    { id: 'c16', author: 'GlobalObserver', text: 'Watching this from Europe. These issues are affecting everyone worldwide.', likeCount: 89, publishedAt: new Date().toISOString(), isReply: false, botScore: 7, classification: 'human', signals: [] },
    { id: 'c17', author: 'user3312984', text: 'AMAZING CONTENT LIKE AND SUBSCRIBE NOW!!!', likeCount: 0, publishedAt: new Date().toISOString(), isReply: false, botScore: 72, classification: 'bot', signals: ['Excessive capitalization', 'Repetitive punctuation pattern', 'Auto-generated username pattern detected', 'Generic low-effort comment'] },
    { id: 'c18', author: 'CriticalThinker', text: 'I disagree with the conclusion but the reporting is fair.', likeCount: 34, publishedAt: new Date().toISOString(), isReply: false, botScore: 6, classification: 'human', signals: [] },
    { id: 'c19', author: 'acc992211334', text: 'Everyone needs to see this video. Share it before they take it down!', likeCount: 2, publishedAt: new Date().toISOString(), isReply: false, botScore: 65, classification: 'bot', signals: ['Near-identical to 7 other comments', 'Auto-generated username pattern detected'] },
    { id: 'c20', author: 'acc992211335', text: 'Everyone needs to see this video. Share it before they take it down!', likeCount: 1, publishedAt: new Date().toISOString(), isReply: false, botScore: 78, classification: 'bot', signals: ['Exact duplicate of 6 other comments', 'Auto-generated username pattern detected'] },
  ],
  clusters: [
    {
      id: 'cl1',
      narrative: '"Great video! Check out my channel for more amazing content like this!"',
      commentCount: 9,
      confidence: 0.96,
      sampleComments: [
        'Great video! Check out my channel for more amazing content like this! https://bit.ly/xyz',
        'Great video! Check out my channel for more amazing content like this! https://bit.ly/abc',
        'Great video! Check out my channel for more content! https://bit.ly/def',
      ],
    },
    {
      id: 'cl2',
      narrative: '"Everyone needs to see this video. Share it before they take it down!"',
      commentCount: 7,
      confidence: 0.88,
      sampleComments: [
        'Everyone needs to see this video. Share it before they take it down!',
        'Everyone needs to see this video! Share before they remove it!',
        'Everyone should see this. Share it before they take it down!',
      ],
    },
    {
      id: 'cl3',
      narrative: '"This content is so informative. Share this everywhere so people know the truth!"',
      commentCount: 5,
      confidence: 0.82,
      sampleComments: [
        'This content is so informative. Share this everywhere so people know the truth!',
        'This content is very informative. Please share everywhere so people know the truth!',
        'Such informative content. Share everywhere so people can know the truth!',
      ],
    },
  ],
  stats: {
    total: 20,
    bots: 11,
    suspicious: 3,
    humans: 6,
    botPercentage: 55,
  },
};
